name: Queue Hold
'on':
  pull_request:
permissions: {}
jobs:
  hold:
    if: startsWith(github.head_ref, 'mergify/merge-queue/') == false && github.event.pull_request.title != 'VM1_DRAFTBOT_CONFIG_REVOKE_260915'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo HOLD_START
          sleep 180
          echo HOLD_DONE
